### ISSUE TITLE
(시스템 관점)요구사항 명세서(=시스템 기획서) 문서화

### ISSUE THREAD

**Issue by MultiDCP** [TimmyRoom/TimmyRoom#19]

**Comment by EunhoKang** [comment]
https://www.notion.so/VR-fd5c155dad6447468978faffcdb4ca4c
글로벌 시스템 관련 요구 사항 추가했습니다.

**Comment by EunhoKang** [comment]
1차적으로 필요한 내용은 모두 수정했습니다.
https://github.com/TimmyRoom/TimmyRoom/blob/develop/Documents/API/API%20%EB%AC%B8%EC%84%9C.md
이상으로 해당 문서 이슈를 닫으며, 추가로 작업이 크게 필요할 경우 다시 이슈를 열겠습니다.
